#sudo: required

os: linux

language: generic

dist: Bionic

services:
  - docker

before_install:
  - docker build -t deutschkihun/portfolio -f ./frontend/Dockerfile.dev ./frontend

after_success:
  - docker build -t deutschkihun/docker-frontend ./frontend
  - docker build -t deutschkihun/docker-backend ./backend
  - docker build -t deutschkihun/docker-nginx ./nginx

  - echo "$DOCKER_HUB_PASSWORD" | docker login -u "$DOCKER_HUB_ID" --password-stdin

  - docker push deutschkihun/docker-frontend
  - docker push deutschkihun/docker-backend
  - docker push deutschkihun/docker-nginx

deploy:
  provider: elasticbeanstalk
  region: "eu-central-1"
  app: "kihunkim-portfolio"
  env: "KihunkimPortfolio-env"
  bucket_name: elasticbeanstalk-eu-central-1-183248202880
  bucket_path: "kihunkim-portfolio"
  on:
    branch: main

  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_ACCESS_KEY
