version: "3"
services:
  frontend:
    build:
      dockerfile: Dockerfile.dev
      context: ./frontend
    volumes:
      - /app/node_modules
      - ./frontend:/app
    stdin_open: true

  nginx:
    restart: always
    build:
      dockerfile: Dockerfile
      context: ./nginx
    ports:
      - "3000:80"

  backend:
    restart: always
    build:
      dockerfile: Dockerfile.dev
      context: ./backend
    container_name: app_backend
    ports:
      - "5000:5000"
    volumes:
      - /app/node_modules
      - ./backend:/app
    environment:
      - MONGO_URI: "mongodb+srv://deutschkihun2:rlgns48126@kihun.0wyb3.mongodb.net/<dbname>?retryWrites=true&w=majority"
      - NODE_ENV: "production"
